# 03.01 - NumPy: Arrays Básicos

**Autor:** Miguel Ángel Vázquez Varela  
**Nivel:** Fundamentos  
**Tiempo estimado:** 25 min

---

## ¿Qué aprenderás?

- Qué es NumPy y por qué usarlo
- Crear arrays de diferentes formas
- Entender shapes y dimensiones
- Tipos de datos en NumPy

---

## 1. ¿Por qué NumPy?

NumPy es la base del análisis de datos en Python. Las listas de Python son lentas para operaciones numéricas.

In [1]:
import numpy as np

### Comparación: lista vs array

In [2]:
# Con listas: necesitas un loop
durations_list = [15, 22, 8, 35, 12]
doubled_list = [x * 2 for x in durations_list]
print(f"Lista x2: {doubled_list}")

Lista x2: [30, 44, 16, 70, 24]


In [3]:
# Con NumPy: operación directa
durations_array = np.array([15, 22, 8, 35, 12])
doubled_array = durations_array * 2
print(f"Array x2: {doubled_array}")

Array x2: [30 44 16 70 24]


NumPy es **mucho más rápido** porque las operaciones se ejecutan en C, no en Python.

---

## 2. Crear arrays

### Desde una lista

In [4]:
# Array 1D
arr = np.array([1, 2, 3, 4, 5])
print(f"Array: {arr}")
print(f"Tipo: {type(arr)}")

Array: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>


In [5]:
# Array 2D (matriz)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"Matriz:\n{matrix}")

Matriz:
[[1 2 3]
 [4 5 6]]


### Arrays con valores predefinidos

In [6]:
# Ceros
zeros = np.zeros(5)
print(f"Zeros: {zeros}")

Zeros: [0. 0. 0. 0. 0.]


In [7]:
# Unos
ones = np.ones((2, 3))  # 2 filas, 3 columnas
print(f"Ones:\n{ones}")

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Valor específico
filled = np.full((2, 2), 7)
print(f"Filled con 7:\n{filled}")

Filled con 7:
[[7 7]
 [7 7]]


### Secuencias

In [9]:
# arange: similar a range()
seq = np.arange(0, 10, 2)  # inicio, fin, paso
print(f"Arange: {seq}")

Arange: [0 2 4 6 8]


In [10]:
# linspace: N valores espaciados uniformemente
lin = np.linspace(0, 1, 5)  # 5 valores entre 0 y 1
print(f"Linspace: {lin}")

Linspace: [0.   0.25 0.5  0.75 1.  ]


### Arrays aleatorios

In [11]:
# Enteros aleatorios
random_ints = np.random.randint(1, 100, size=5)
print(f"Aleatorios (1-100): {random_ints}")

Aleatorios (1-100): [30 63 50 93 17]


In [12]:
# Distribución normal
normal = np.random.normal(loc=50, scale=10, size=5)  # media=50, std=10
print(f"Normal: {normal}")

Normal: [32.56532478 40.44706117 46.62002558 60.4980163  48.28601144]


---

## 3. Shape y dimensiones

El **shape** define la estructura del array.

In [13]:
# Array 1D
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"Array: {arr_1d}")
print(f"Shape: {arr_1d.shape}")
print(f"Dimensiones: {arr_1d.ndim}")

Array: [1 2 3 4 5]
Shape: (5,)
Dimensiones: 1


In [14]:
# Array 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array:\n{arr_2d}")
print(f"Shape: {arr_2d.shape}")  # (filas, columnas)
print(f"Dimensiones: {arr_2d.ndim}")

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensiones: 2


### Reshape: cambiar la forma

In [15]:
# Array de 12 elementos
arr = np.arange(12)
print(f"Original: {arr}")
print(f"Shape: {arr.shape}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)


In [16]:
# Convertir a 3x4
reshaped = arr.reshape(3, 4)
print(f"Reshaped (3x4):\n{reshaped}")

Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
# Convertir a 4x3
reshaped2 = arr.reshape(4, 3)
print(f"Reshaped (4x3):\n{reshaped2}")

Reshaped (4x3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
# Usar -1 para calcular automáticamente
reshaped3 = arr.reshape(2, -1)  # 2 filas, columnas automáticas
print(f"Reshaped (2, -1):\n{reshaped3}")

Reshaped (2, -1):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


---

## 4. Tipos de datos (dtype)

NumPy tiene tipos de datos específicos para optimizar memoria y velocidad.

In [19]:
# Por defecto: int64 o float64
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])

print(f"Enteros dtype: {arr_int.dtype}")
print(f"Floats dtype: {arr_float.dtype}")

Enteros dtype: int64
Floats dtype: float64


In [20]:
# Especificar tipo
arr_32 = np.array([1, 2, 3], dtype=np.float32)
print(f"Float32: {arr_32.dtype}")

Float32: float32


In [21]:
# Convertir tipo
arr = np.array([1.7, 2.3, 3.9])
arr_int = arr.astype(int)
print(f"Original: {arr}")
print(f"Como int: {arr_int}")

Original: [1.7 2.3 3.9]
Como int: [1 2 3]


### Tipos comunes

| Tipo | Descripción |
|------|-------------|
| `int32`, `int64` | Enteros |
| `float32`, `float64` | Decimales |
| `bool` | Booleanos |
| `str` | Strings |

---

## 5. Atributos útiles

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Shape: {arr.shape}")      # (filas, columnas)
print(f"Dimensiones: {arr.ndim}") # número de dimensiones
print(f"Tamaño: {arr.size}")      # total de elementos
print(f"Dtype: {arr.dtype}")      # tipo de datos

Shape: (2, 3)
Dimensiones: 2
Tamaño: 6
Dtype: int64


---

## 💡 Resumen

| Función | Uso | Ejemplo |
|---------|-----|--------|
| `np.array()` | Crear desde lista | `np.array([1,2,3])` |
| `np.zeros()` | Array de ceros | `np.zeros((2,3))` |
| `np.ones()` | Array de unos | `np.ones(5)` |
| `np.arange()` | Secuencia | `np.arange(0,10,2)` |
| `np.linspace()` | N valores uniformes | `np.linspace(0,1,5)` |
| `.reshape()` | Cambiar forma | `arr.reshape(2,3)` |

---

## 🏋️ Ejercicio

1. Crea un array con las duraciónes de 10 viajes (valores aleatorios entre 5 y 60 minutos)
2. Muestra el shape, dtype y tamaño
3. Reshapea a una matriz de 2x5

In [23]:
# Tu código aquí
durations = np.random.randint(5, 61, size=10)
print(f"Duraciones: {durations}")
print(f"Shape: {durations.shape}")
print(f"Dtype: {durations.dtype}")
print(f"Tamaño: {durations.size}")

# Reshape a 2x5
matrix = durations.reshape(2, 5)
print(f"\nMatriz 2x5:\n{matrix}")

Duraciones: [13 19 32 59 11 51 23 59 35 27]
Shape: (10,)
Dtype: int32
Tamaño: 10

Matriz 2x5:
[[13 19 32 59 11]
 [51 23 59 35 27]]


---

**Anterior:** [02.03 - Modulos y Paquetes](../02_functions_and_modules/02_03_modules_and_packages.ipynb)  
**Siguiente:** [03.02 - Indexing y Slicing](./03_02_indexing_slicing.ipynb)