# 03.03 - NumPy: Operaciones

**Autor:** Miguel Ángel Vázquez Varela  
**Nivel:** Fundamentos  
**Tiempo estimado:** 25 min

---

## ¿Qué aprenderás?

- Operaciones vectorizadas (elemento a elemento)
- Funciones de agregación (sum, mean, etc.)
- Broadcasting
- Operaciones con múltiples arrays

In [1]:
import numpy as np

---

## 1. Operaciones vectorizadas

Las operaciones se aplican a **todos los elementos** automáticamente. Sin loops.

### Operaciones aritméticas

In [2]:
durations = np.array([15, 22, 8, 35, 12])
print(f"Duraciones: {durations}")

Duraciones: [15 22  8 35 12]


In [3]:
# Sumar 5 a todos
print(f"+ 5: {durations + 5}")

+ 5: [20 27 13 40 17]


In [4]:
# Multiplicar por 2
print(f"x 2: {durations * 2}")

x 2: [30 44 16 70 24]


In [5]:
# Convertir minutos a horas
hours = durations / 60
print(f"En horas: {hours}")

En horas: [0.25       0.36666667 0.13333333 0.58333333 0.2       ]


In [6]:
# Potencia
print(f"Al cuadrado: {durations ** 2}")

Al cuadrado: [ 225  484   64 1225  144]


### Comparaciones

In [7]:
print(f"¿Mayor que 20?: {durations > 20}")

¿Mayor que 20?: [False  True False  True False]


In [8]:
print(f"¿Igual a 15?: {durations == 15}")

¿Igual a 15?: [ True False False False False]


---

## 2. Funciones de agregación

Resumen de todo el array en un solo valor.

In [9]:
durations = np.array([15, 22, 8, 35, 12, 45, 18])
print(f"Duraciones: {durations}")

Duraciones: [15 22  8 35 12 45 18]


In [10]:
print(f"Suma: {np.sum(durations)}")
print(f"Media: {np.mean(durations):.2f}")
print(f"Mediana: {np.median(durations)}")

Suma: 155
Media: 22.14
Mediana: 18.0


In [11]:
print(f"Mínimo: {np.min(durations)}")
print(f"Máximo: {np.max(durations)}")
print(f"Rango: {np.ptp(durations)}")  # peak to peak (max - min)

Mínimo: 8
Máximo: 45
Rango: 37


In [12]:
print(f"Desviación estándar: {np.std(durations):.2f}")
print(f"Varianza: {np.var(durations):.2f}")

Desviación estándar: 12.30
Varianza: 151.27


### Índices de min/max

In [13]:
print(f"Índice del mínimo: {np.argmin(durations)}")
print(f"Índice del máximo: {np.argmax(durations)}")

Índice del mínimo: 2
Índice del máximo: 5


### Agregación por eje (en 2D)

In [14]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(f"Matriz:\n{matrix}")

Matriz:
[[10 20 30]
 [40 50 60]]


In [15]:
# Suma total
print(f"Suma total: {np.sum(matrix)}")

Suma total: 210


In [16]:
# Suma por columnas (axis=0: colapsa filas)
print(f"Suma por columna: {np.sum(matrix, axis=0)}")

Suma por columna: [50 70 90]


In [17]:
# Suma por filas (axis=1: colapsa columnas)
print(f"Suma por fila: {np.sum(matrix, axis=1)}")

Suma por fila: [ 60 150]


---

## 3. Operaciones entre arrays

Si tienen el mismo shape, opera elemento a elemento.

In [18]:
distances = np.array([3.5, 5.2, 2.1, 8.0, 4.5])  # km
durations = np.array([15, 22, 8, 35, 12])        # minutos

print(f"Distancias: {distances}")
print(f"Duraciones: {durations}")

Distancias: [3.5 5.2 2.1 8.  4.5]
Duraciones: [15 22  8 35 12]


In [19]:
# Velocidad = distancia / tiempo (en horas)
speeds = distances / (durations / 60)
print(f"Velocidades (km/h): {speeds}")

Velocidades (km/h): [14.         14.18181818 15.75       13.71428571 22.5       ]


In [20]:
# Suma de arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(f"Suma: {arr1 + arr2}")

Suma: [5 7 9]


---

## 4. Broadcasting

NumPy puede operar arrays de diferentes shapes "expandiendo" el más pequeño.

In [21]:
# Escalar + array: el escalar se "expande"
arr = np.array([1, 2, 3])
print(f"arr + 10: {arr + 10}")

arr + 10: [11 12 13]


### Broadcasting en 2D

In [22]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"Matriz:\n{matrix}")

Matriz:
[[1 2 3]
 [4 5 6]]


In [23]:
# Sumar un vector a cada fila
row = np.array([10, 20, 30])
result = matrix + row
print(f"Matriz + [10,20,30]:\n{result}")

Matriz + [10,20,30]:
[[11 22 33]
 [14 25 36]]


In [24]:
# Sumar un vector a cada columna
col = np.array([[100], [200]])  # Nota: shape (2, 1)
result = matrix + col
print(f"Matriz + columna:\n{result}")

Matriz + columna:
[[101 102 103]
 [204 205 206]]


---

## 5. Funciones matemáticas

In [25]:
arr = np.array([1, 4, 9, 16, 25])

In [26]:
# Raíz cuadrada
print(f"Raíz: {np.sqrt(arr)}")

Raíz: [1. 2. 3. 4. 5.]


In [27]:
# Exponencial
print(f"e^arr: {np.exp(arr)}")

e^arr: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [28]:
# Logaritmo
print(f"log(arr): {np.log(arr)}")

log(arr): [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [29]:
# Redondeo
floats = np.array([1.2, 2.7, 3.5, 4.1])
print(f"Original: {floats}")
print(f"Round: {np.round(floats)}")
print(f"Floor: {np.floor(floats)}")
print(f"Ceil: {np.ceil(floats)}")

Original: [1.2 2.7 3.5 4.1]
Round: [1. 3. 4. 4.]
Floor: [1. 2. 3. 4.]
Ceil: [2. 3. 4. 5.]


---

## 6. Funciones útiles

### where: condicional vectorizado

In [30]:
durations = np.array([15, 22, 8, 35, 12])

# Si > 20: 'largo', sino: 'corto'
labels = np.where(durations > 20, 'largo', 'corto')
print(f"Etiquetas: {labels}")

Etiquetas: ['corto' 'largo' 'corto' 'largo' 'corto']


### clip: limitar valores

In [31]:
values = np.array([5, 15, 25, 35, 45])

# Limitar entre 10 y 30
clipped = np.clip(values, 10, 30)
print(f"Original: {values}")
print(f"Clipped (10-30): {clipped}")

Original: [ 5 15 25 35 45]
Clipped (10-30): [10 15 25 30 30]


### unique: valores únicos

In [32]:
stations = np.array(["Sol", "Atocha", "Sol", "Cibeles", "Atocha"])

unique = np.unique(stations)
print(f"Únicos: {unique}")

Únicos: ['Atocha' 'Cibeles' 'Sol']


In [33]:
# Con conteos
unique, counts = np.unique(stations, return_counts=True)
for station, count in zip(unique, counts):
    print(f"{station}: {count}")

Atocha: 2
Cibeles: 1
Sol: 2


---

## 💡 Resumen

| Función | Descripción |
|---------|-------------|
| `np.sum()` | Suma |
| `np.mean()` | Media |
| `np.std()` | Desviación estándar |
| `np.min()`, `np.max()` | Mínimo, máximo |
| `np.argmin()`, `np.argmax()` | Índice de min/max |
| `np.where()` | Condicional vectorizado |
| `np.clip()` | Limitar valores |
| `np.unique()` | Valores únicos |

---

## 🏋️ Ejercicio

Tienes velocidades de viajes (km/h). Calcula:
1. Velocidad media y desviación estándar
2. Cuántos viajes superan los 15 km/h
3. Etiqueta como 'lento' (<10), 'normal' (10-20), 'rápido' (>20)

In [34]:
speeds = np.array([8.5, 12.3, 22.1, 15.0, 9.8, 18.5, 25.0, 11.2])
print(f"Velocidades: {speeds}")

# 1. Media y std
print(f"\nMedia: {np.mean(speeds):.2f} km/h")
print(f"Std: {np.std(speeds):.2f} km/h")

# 2. Cuántos > 15
fast_count = np.sum(speeds > 15)
print(f"\nViajes > 15 km/h: {fast_count}")

# 3. Etiquetas
labels = np.where(speeds < 10, 'lento',
         np.where(speeds <= 20, 'normal', 'rápido'))
print(f"\nEtiquetas: {labels}")

Velocidades: [ 8.5 12.3 22.1 15.   9.8 18.5 25.  11.2]

Media: 15.30 km/h
Std: 5.62 km/h

Viajes > 15 km/h: 3

Etiquetas: ['lento' 'normal' 'rápido' 'normal' 'lento' 'normal' 'rápido' 'normal']


---

**Anterior:** [03.02 - Indexing y Slicing](./03_02_indexing_slicing.ipynb)  
**Siguiente:** [04.01 - Pandas Basics](../04_pandas_basics/04_01_series_dataframes.ipynb)