# 03.02 - NumPy: Indexing y Slicing

**Autor:** Miguel Ángel Vázquez Varela  
**Nivel:** Fundamentos  
**Tiempo estimado:** 20 min

---

## ¿Qué aprenderás?

- Acceder a elementos individuales
- Extraer subconjuntos con slicing
- Indexing con arrays booleanos
- Fancy indexing

In [1]:
import numpy as np

---

## 1. Indexing básico (1D)

Similar a listas de Python. Los índices empiezan en **0**.

In [2]:
durations = np.array([15, 22, 8, 35, 12, 45, 18])
print(f"Array: {durations}")

Array: [15 22  8 35 12 45 18]


In [3]:
# Primer elemento
print(f"Primero: {durations[0]}")

Primero: 15


In [4]:
# Último elemento
print(f"Último: {durations[-1]}")

Último: 18


In [5]:
# Penúltimo
print(f"Penúltimo: {durations[-2]}")

Penúltimo: 45


---

## 2. Slicing (1D)

Sintaxis: `array[inicio:fin:paso]`

- `inicio`: incluido
- `fin`: **NO incluido**
- `paso`: opcional

In [6]:
durations = np.array([15, 22, 8, 35, 12, 45, 18])
print(f"Array: {durations}")

Array: [15 22  8 35 12 45 18]


In [7]:
# Primeros 3 elementos
print(f"Primeros 3: {durations[:3]}")

Primeros 3: [15 22  8]


In [8]:
# Desde el 3º hasta el final
print(f"Desde el 3º: {durations[2:]}")

Desde el 3º: [ 8 35 12 45 18]


In [9]:
# Del 2º al 5º (índices 1-4)
print(f"Del 2º al 5º: {durations[1:5]}")

Del 2º al 5º: [22  8 35 12]


In [10]:
# Cada 2 elementos
print(f"Cada 2: {durations[::2]}")

Cada 2: [15  8 12 18]


In [11]:
# Invertir el array
print(f"Invertido: {durations[::-1]}")

Invertido: [18 45 12 35  8 22 15]


---

## 3. Indexing en 2D

Usa `[fila, columna]`.

In [12]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(f"Matriz:\n{matrix}")
print(f"Shape: {matrix.shape}")

Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [13]:
# Elemento en fila 0, columna 2
print(f"[0, 2]: {matrix[0, 2]}")

[0, 2]: 3


In [14]:
# Última fila, última columna
print(f"[-1, -1]: {matrix[-1, -1]}")

[-1, -1]: 12


### Seleccionar filas o columnas completas

In [15]:
# Primera fila
print(f"Fila 0: {matrix[0, :]}")
# Equivalente:
print(f"Fila 0: {matrix[0]}")

Fila 0: [1 2 3 4]
Fila 0: [1 2 3 4]


In [16]:
# Segunda columna
print(f"Columna 1: {matrix[:, 1]}")

Columna 1: [ 2  6 10]


### Slicing en 2D

In [17]:
# Submatriz: filas 0-1, columnas 1-2
sub = matrix[0:2, 1:3]
print(f"Submatriz:\n{sub}")

Submatriz:
[[2 3]
 [6 7]]


In [18]:
# Primeras 2 filas, todas las columnas
print(f"Primeras 2 filas:\n{matrix[:2, :]}")

Primeras 2 filas:
[[1 2 3 4]
 [5 6 7 8]]


---

## 4. Boolean indexing (máscaras)

Muy poderoso para filtrar datos. Usarás esto **constantemente** en Pandas.

In [19]:
durations = np.array([15, 22, 8, 35, 12, 45, 18])
print(f"Duraciones: {durations}")

Duraciones: [15 22  8 35 12 45 18]


### Crear una máscara booleana

In [20]:
# ¿Cuáles son mayores que 20?
mask = durations > 20
print(f"Máscara (>20): {mask}")

Máscara (>20): [False  True False  True False  True False]


### Aplicar la máscara

In [21]:
# Filtrar: solo los mayores que 20
long_trips = durations[mask]
print(f"Viajes largos (>20): {long_trips}")

Viajes largos (>20): [22 35 45]


In [22]:
# En una línea (más común)
long_trips = durations[durations > 20]
print(f"Viajes largos: {long_trips}")

Viajes largos: [22 35 45]


### Condiciones combinadas

In [23]:
# Entre 10 y 30 minutos
# Usa & (and) y | (or), NO 'and' y 'or'
medium = durations[(durations >= 10) & (durations <= 30)]
print(f"Viajes medios (10-30): {medium}")

Viajes medios (10-30): [15 22 12 18]


In [24]:
# Menores que 10 O mayores que 40
extreme = durations[(durations < 10) | (durations > 40)]
print(f"Viajes extremos (<10 o >40): {extreme}")

Viajes extremos (<10 o >40): [ 8 45]


---

## 5. Fancy indexing

Seleccionar múltiples elementos usando una lista de índices.

In [25]:
stations = np.array(["Sol", "Atocha", "Cibeles", "Retiro", "Moncloa"])
print(f"Estaciones: {stations}")

Estaciones: ['Sol' 'Atocha' 'Cibeles' 'Retiro' 'Moncloa']


In [26]:
# Seleccionar índices 0, 2 y 4
indices = [0, 2, 4]
selected = stations[indices]
print(f"Seleccionadas: {selected}")

Seleccionadas: ['Sol' 'Cibeles' 'Moncloa']


In [27]:
# En una línea
print(f"Seleccionadas: {stations[[0, 2, 4]]}")

Seleccionadas: ['Sol' 'Cibeles' 'Moncloa']


---

## 6. Modificar valores

In [28]:
arr = np.array([1, 2, 3, 4, 5])
print(f"Original: {arr}")

Original: [1 2 3 4 5]


In [29]:
# Modificar un elemento
arr[0] = 100
print(f"Después de arr[0]=100: {arr}")

Después de arr[0]=100: [100   2   3   4   5]


In [30]:
# Modificar con slice
arr[1:3] = [200, 300]
print(f"Después de slice: {arr}")

Después de slice: [100 200 300   4   5]


In [31]:
# Modificar con máscara
arr[arr > 100] = 0
print(f"Valores >100 a 0: {arr}")

Valores >100 a 0: [100   0   0   4   5]


---

## 💡 Resumen

| Operación | Sintaxis | Ejemplo |
|-----------|----------|--------|
| Elemento | `arr[i]` | `arr[0]` |
| Slice | `arr[i:j]` | `arr[1:4]` |
| Paso | `arr[::n]` | `arr[::2]` |
| 2D | `arr[i, j]` | `arr[0, 2]` |
| Fila | `arr[i, :]` | `arr[0, :]` |
| Columna | `arr[:, j]` | `arr[:, 1]` |
| Máscara | `arr[cond]` | `arr[arr > 5]` |

---

## 🏋️ Ejercicio

Tienes duraciones de viajes. Filtra:
1. Viajes de menos de 10 minutos
2. Viajes entre 15 y 30 minutos
3. Reemplaza los viajes de más de 40 min por 40 (cap)

In [32]:
durations = np.array([5, 18, 42, 12, 55, 8, 25, 33])
print(f"Original: {durations}")

# 1. Menos de 10 min
short = durations[durations < 10]
print(f"Cortos (<10): {short}")

# 2. Entre 15 y 30
medium = durations[(durations >= 15) & (durations <= 30)]
print(f"Medios (15-30): {medium}")

# 3. Cap a 40
capped = durations.copy()
capped[capped > 40] = 40
print(f"Capped (max 40): {capped}")

Original: [ 5 18 42 12 55  8 25 33]
Cortos (<10): [5 8]
Medios (15-30): [18 25]
Capped (max 40): [ 5 18 40 12 40  8 25 33]


---

**Anterior:** [03.01 - Arrays Básicos](./03_01_arrays_basics.ipynb)  
**Siguiente:** [03.03 - Operaciones](./03_03_operations.ipynb)